login to ECR

diff --git a/.github/workflows/start-runner.yml b/.github/workflows/start-runner.yml
--- a/.github/workflows/start-runner.yml
+++ b/.github/workflows/start-runner.yml
@@ -63,9 +63,14 @@ jobs:
             role-to-assume: arn:aws:iam::585768185180:role/github_oidc_role
             aws-region: ${{ vars.AWS_REGION }}
 
+
       - name: Login to Amazon ECR
-        run: |
-            aws ecr get-login-password --region ${{ vars.AWS_REGION }} | docker login --username AWS --password-stdin ${{ vars.ECR_REPO_URL }}
+        id: login-ecr
+        uses: aws-actions/amazon-ecr-login@v2
+
+    #   - name: Login to Amazon ECR
+    #     run: |
+    #         aws ecr get-login-password --region ${{ vars.AWS_REGION }} | docker login --username AWS --password-stdin ${{ vars.ECR_REPO_URL }}
 
       - name: Build, tag, and push docker image to Amazon ECR
         env:
@@ -75,3 +80,33 @@ jobs:
         run: |
             docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
             docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
+
+
+  deploy:
+    name: Deploy to EKS
+    runs-on: ${{ needs.start-runner.outputs.label }}
+
+    steps:
+
+
+
+        - name: Read commit hash
+        id: read-commit-hash
+        run: |
+            export COMMIT_HASH=$(cat commit_hash.txt)
+            echo "commit_hash=$COMMIT_HASH" >> $GITHUB_ENV
+
+        - name: Checkout repository
+        uses: actions/checkout@v4
+    
+
+        - name: Verify image exists
+        env:
+            REGISTRY: ${{ vars.ECR_REPO_URL }}
+            REPOSITORY: ${{ vars.REPO_NAME }}
+            IMAGE_TAG: ${{ env.commit_hash }}
+        run: |
+            aws ecr describe-images \
+            --repository-name ${REPOSITORY} \
+            --image-ids imageTag=${IMAGE_TAG} \
+            || { echo "Image tag ${IMAGE_TAG} not found in ECR"; exit 1; }            
